### ISSUE TITLE
Flash messages

### ISSUE THREAD

**Issue by liha16** [1dv611-vt21-g5/1dv611-project#109]
**Tidsuppskattning:** 4 timmar

------
På något sätt måste använder få reda på om saker går rätt eller fel. "subscription added", "text copied" osv... Borde vi inte fixa flash messages?

**Comment by akarlsten** [comment]
Jo, bra tänkt! Chakra har en inbyggd Toast-komponent vi kan använda: https://chakra-ui.com/docs/feedback/toast

**Comment by akarlsten** [comment]
Har lagt till även till reset API key
